### ISSUE TITLE
Running Python run_all.py error

### ISSUE THREAD

**Issue by laisenglee** [facebook/Surround360#251]
laiseng@laiseng-Precision-Rack-7910:~/Surround360/surround360_render/scripts$ python run_all.py
Traceback (most recent call last):
  File "run_all.py", line 32, in <module>
    if USE_GOOEY: from gooey import Gooey, GooeyParser # only load Gooey if needed
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/__init__.py", line 2, in <module>
    from gooey.python_bindings.gooey_decorator import Gooey
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 14, in <module>
    from gooey.gui import application
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/gui/application.py", line 8, in <module>
    from gooey.gui.controller import Controller
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/gui/controller.py", line 2, in <module>
    from gooey.gui.presenter import Presenter
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/gui/presenter.py", line 3, in <module>
    from gooey.gui.processor import ProcessController
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/gui/processor.py", line 13, in <module>
    from gooey.gui.util.taskkill import taskkill
  File "/usr/local/lib/python2.7/dist-packages/Gooey-0.9.5.2-py2.7.egg/gooey/gui/util/taskkill.py", line 10, in <module>
    import psutil
ImportError: No module named psutil
laiseng@laiseng-Precision-Rack-7910:~/Surround360/surround360_render/scripts$ ^C
laiseng@laiseng-Precision-Rack-7910:~/Surround360/surround360_render/scripts$

**Comment by Supremes** [comment]
just install psutil module
